// demo-vue/src/components/App.vue
<template>
  <Page actionBarHidden="true">
    <GridLayout rows="auto,*,auto" columns="*" height="100%">
      <Label text="Approov Shapes" class="heading" row="0"></Label>
      <!-- Image Container -->
      <StackLayout orientation="vertical" horizontalAlignment="center" verticalAlignment="center" row="1">
        <Image :src="imageUrl"></Image>

        <Label :text="message" textWrap="true" class="text-center sub-text"></Label>
      </StackLayout>
      <FlexboxLayout col="0" row="2" justifyContent="space-around" margin="20">
        <!-- Buttons -->
        <Button text="Hello" @tap="onHelloButtonTap()" class="-primary -rounded-lg" padding="5"></Button>
        <Button text="Shape" @tap="onShapeButtonTap()" class="-primary -rounded-lg" padding="5"></Button>
      </FlexboxLayout>
    </GridLayout>

  </Page>
</template>

<script lang="ts">
/* Uncomment for Approov */
// import { NSApproov } from '@approov/ns-approov-sdk';

import * as HttpModule from '@nativescript/core/http';

const VERSION = 'v1'; // use v2 for Approov

const HELLO_URL = `https://shapes.approov.io/${VERSION}/hello`;
const SHAPE_URL = `https://shapes.approov.io/${VERSION}/shapes`;

export default {
  data() {
    return {
      message: 'Tap Hello to Start...',
      imageUrl: '~/assets/approov.png',
    }
  },
  methods: {
    onHelloButtonTap() {
      HttpModule.getJSON<any>({
        method: 'GET',
        url: HELLO_URL
      })
      .then((response) => {
        console.log('Hello API Success Response => ', response);
        this.message = response.status;
        this.imageUrl = '~/assets/hello.png';
      })
      .catch((error) => {
        console.log('Hello API Error Response => ', error);
        this.message = `Error: ${error.statusCode}, Message: ${error.reason}`;
        this.imageUrl = '~/assets/confused.png';
      });
    },
    onShapeButtonTap() {
      HttpModule.getJSON<any>({ // Comment when Using Approov
        method: 'GET',
        url: SHAPE_URL
      }).then((resp) => resp.shape ? resp : Promise.reject(resp))

      /* Uncomment for Approov */

      // NSApproov.request({
      //   method: 'GET',
      //   url: SHAPE_URL,
      //   headers: {Authorization: 'token-data'},
      // }).then((resp) => resp.content)
      .then((response) => {
        console.log('Shapes API Success Response => ', response);
        this.message = response.status;
        this.imageUrl = `~/assets/${response.shape.toLowerCase()}.png`;
      })
      .catch((err) => {
        console.log('Shapes API Error Response => ', err);
        this.message = `Error: ${err.statusCode}, Message: ${err.reason}`;
        this.imageUrl = '~/assets/confused.png';
      });
    },
  },
}
</script>

// demo-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';

@Component({
    selector: 'ns-app',
    templateUrl: './app.component.html'
})
export class AppComponent {
  readonly imageBaseUrl = '~/assets/';
  readonly imageExtension = 'png';
  readonly VERSION = 'v1'; // Change To v2 when using Approov
  readonly HELLO_URL = `https://shapes.approov.io/${this.VERSION}/hello`;
  readonly SHAPE_URL = `https://shapes.approov.io/${this.VERSION}/shapes`;

  private image = 'approov';

  message = 'Tap Hello to Start...';
  imageUrl = this.getImageUrl(this.image);

  constructor(private httpClient: HttpClient) {
  }

  onHelloButtonTap(): void {
    this.httpClient.get(this.HELLO_URL, { headers: { Authorization: 'key-token' } }).subscribe({
      next: (response: { text: string; message: string }) => {
        console.log('Response => ', response);
        this.message = response.text;
        this.imageUrl = this.getImageUrl('hello');
      },
      error: (errorResponse: HttpErrorResponse) => {
        console.log('HTTP ERROR HELLO => ', errorResponse);
        this.message = `Error: ${errorResponse.status}, Message: ${errorResponse.statusText}`;
        this.imageUrl = this.getImageUrl('confused');
      }
    });
  }

  onShapeButtonTap(): void {
    this.httpClient.get(this.SHAPE_URL, { headers: { Authorization: 'key-token' } }).subscribe({
      next: (response: any) => {
        console.log('Response => ', response);
        this.message = response.status;
        this.imageUrl = this.getImageUrl(response.shape.toLowerCase());
      },
      error: (err: HttpErrorResponse) => {
        console.log('Shapes API Error Response => ', err);
        this.message = `Error: ${err.status}, Message: ${err.statusText}`;
        this.imageUrl = this.getImageUrl('confused');
      }
    });
  }

  getImageUrl(name: string): string {
    return `${this.imageBaseUrl}${name}.${this.imageExtension}`;
  }
}

<GridLayout rows="auto,*,auto" columns="*" height="100%">
    <Label text="Approov Shapes" class="heading" row="0"></Label>
    <!-- Image Container -->
    <StackLayout orientation="vertical" horizontalAlignment="center" verticalAlignment="center" row="1">
        <Image src="{{ imageUrl }}"></Image>

        <Label text="{{ message }}" textWrap="true" class="text-center sub-text"></Label>
    </StackLayout>
    <FlexboxLayout col="0" row="2" justifyContent="space-around" margin="20">
        <!-- Buttons -->
        <Button text="Hello" (tap)="onHelloButtonTap()" class="-primary -rounded-lg" padding="5"></Button>
        <Button text="Shape" (tap)="onShapeButtonTap()" class="-primary -rounded-lg" padding="5"></Button>
    </FlexboxLayout>
</GridLayout>
